version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: absurdly_db
    environment:
      POSTGRES_USER: absurdly
      POSTGRES_PASSWORD: correct
      POSTGRES_DB: absurdly_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: absurdly_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://absurdly:correct@db:5432/absurdly_db"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: absurdly_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pgdata:
