"""Initial migration

Revision ID: 099a207bd331
Revises: 
Create Date: 2025-03-06 01:22:56.708855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099a207bd331'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_black_cards_id'), 'black_cards', ['id'], unique=False)
    op.create_index(op.f('ix_white_cards_id'), 'white_cards', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_white_cards_id'), table_name='white_cards')
    op.drop_index(op.f('ix_black_cards_id'), table_name='black_cards')
    # ### end Alembic commands ###
